#!/bin/bash
# $0 [release]
# 
# By default would take a master branch copy and place into file tree here.
# If release is provided, would inject version corresponding to that tagged
# release of bids-specification"

set -eu

rel="$1"  # specify release
repo=${2:-}  # optionally - use the local repo

[ -z "$repo" ] || repo=$(readlink -f "$repo")

cd "$(dirname "$0")/.."

if [ "$rel" = "master" ]; then
	treeish="$rel"
	rm -r versions/"$rel"  # we allow to redo master since it changes
	# TODO: for master would be nice to have output of `git describe` but I do not
	# think we can get that without git clone'ing
else
	treeish="v$rel"
fi

mkdir versions/"$rel"  # must not exist yet
cd versions/"$rel"

if [ -z "$repo" ]; then
    curl --silent -L "https://github.com/bids-standard/bids-specification/tarball/$treeish" \
    | tar -xzf- --strip 2 --wildcards '*/src/schema'
else
    git -C "$repo" archive --prefix prefix/ "$treeish" \
    | tar -xf- --strip 2 --wildcards '*/src/schema'
fi


bst -v export --schema schema --output schema.json

# Generate pretty-printed schema
"$(dirname "$0")/prettify-schema" schema

cd ..

if [ "$rel" != "master" ]; then
    # possibly make it "the latest". very crude and inefficient!!
    latest=$(/bin/ls -1d [1-9].* | sort -V | tail -n 1)
    rm -rf latest
    cp -rp "$latest" latest
fi
