#!/bin/bash
#
# The "ultimate" script to run to do injection, e.g. on CI
#

export PS4='> '
set -x
set -eu
this_path=$(dirname "$0")
versions_path="${this_path}/../versions"

TMP="$(mktemp -d "${TMPDIR:-/tmp}"/bids-XXXXXXX)"
# shellcheck disable=SC2064
trap "rm -rf '$TMP'" SIGINT SIGHUP SIGABRT EXIT

: "${BIDS_REPO:=}"

if [ -z "$BIDS_REPO" ]; then
    BIDS_REPO="$TMP/bids-specification"

    git clone https://github.com/bids-standard/bids-specification/ "$BIDS_REPO"
fi

schema_ver=$("$this_path/version_component.sh" "$BIDS_REPO" src/schema | sed -e 's,^v,,g')

to_inject=''

master_ver_here=$(cat "$versions_path/master/BIDS_VERSION_LASTEDIT" || echo "unknown")
if [ "$master_ver_here" != "$schema_ver" ] ; then
    to_inject+="v$schema_ver master\n"
fi

released_ver=${schema_ver%%+*}
echo "schema version: $schema_ver ; released ver: $released_ver"
if [ ! -d "$versions_path/$released_ver" ]; then
    to_inject+="v$released_ver $released_ver\n"
fi

if [ -n "$to_inject" ]; then
    # TODO: setup venv
    venv="$TMP/venv"
    # shellcheck disable=SC1091
    python3 -m "venv" "$venv" && source "$venv/bin/activate"
    python -m pip install -r requirements.txt
    echo -e "$to_inject" | while read -r committish folder; do
        [ -n "$committish" ] || continue
        set +e
        out=$(git -C "$BIDS_REPO" checkout "$committish" -- 2>&1)
        ex="$?"
        set -e
        if [ "$ex" != 0 ]; then
            if echo "$out" | grep "invalid reference"; then
                # git stopped understanding committishes like v1.10.1+23-g6404e2ee?
                git -C "$BIDS_REPO" checkout "${committish#*[0-9]-g}"
            else
                echo -e "ERROR: errored out with out:\n$out"
                exit 1
            fi
        fi

        "$this_path/inject-schema" "$folder" "$BIDS_REPO"
        version_folder="$versions_path/$folder/"
        echo "$committish" >| "$version_folder/BIDS_VERSION_LASTEDIT"
        schema_version=$(cat "$version_folder/schema/SCHEMA_VERSION")
        bids_version=$(cat "$version_folder/schema/BIDS_VERSION")
        git add versions; 
        if git diff-index --quiet HEAD --; then
            echo "Nothing to commit"
        else
            git commit -m "Injected schema $schema_version for BIDS $bids_version as of commit $committish into versions/$folder" -a
        fi
    done
fi
echo "done"
